spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: YOUR_TENANT_ID
        credential:
          client-id: YOUR_CLIENT_ID
          client-secret: YOUR_CLIENT_SECRET
